spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${db_url}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        show_sql: true
        ddl-auto: true
        temp:
          use_jdbc_metadata_defaults: false
